name: Metrics

on:
  # Génération automatique tous les jours à minuit
  schedule:
    - cron: "0 0 * * *"
  # Permet de lancer manuellement depuis l’onglet Actions
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Le fichier généré
          filename: metrics.svg

          # Token GitHub stocké dans les secrets
          token: ${{ secrets.METRICS_TOKEN }}

          # Configuration de base (GitHub)
          base: header, activity, repositories, metadata
          config_timezone: Europe/Paris

          # Activation du plugin GitLab
          plugin_gitlab: yes
          plugin_gitlab_token: ${{ secrets.GITLAB_TOKEN }}
          plugin_gitlab_user: "senjosakki1"
