name: Metrics

on:
  # Génération automatique tous les jours à minuit
  schedule:
    - cron: "0 0 * * *"
  # Lancer manuellement depuis l’onglet Actions
  workflow_dispatch:

permissions:
  contents: write   # <- important pour pouvoir écrire metrics.svg

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Config de base GitHub
          base: header, activity, repositories, metadata
          config_timezone: Europe/Paris

          # GitLab
          plugin_gitlab: yes
          plugin_gitlab_token: ${{ secrets.GITLAB_TOKEN }}
          plugin_gitlab_user: "senjosakki1"  # remplace ici
