name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # tous les jours à minuit
  workflow_dispatch:       # exécution manuelle

permissions:
  contents: write          # nécessaire pour écrire metrics.svg

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg

          # Base GitHub
          base: header, activity, repositories, metadata
          config_timezone: Europe/Paris

          # Quelques plugins utiles (tous pure GitHub)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, scss
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          plugin_lines: yes
          plugin_lines_history_limit: 1

          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_worldmap: no
